var GAME_LEVELS = [

  ["                                           ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxx ",
   " xxxxxxxx       xxxxxxxxxxxx!!!xxx    xxxx ",
   " xxxx              xxxx    xx!xx        xx ",
   " xx                 xx      xvx          x ",
   " x                  x                    x ",
   " x                                       x ",
   " x                                       x ",
   " x                                       x ",
   " xx  @     o                             x ",
   " xxxxxxxxxxxx p   e       xx   xx     g ox ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxx ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx "],
   
   
  ["                                                                                ",
   "                                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                            xxxxxx         xxxxxxxxxxxxxxxxxxx  ",
   "                                           xxxxx                            xx  ",
   "                                          xxx                               xx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!xxxx                       e    o   xx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!xxxx                     xxxxxxxxxxxxxxx  ",
   "  xxxx                   xxx!!!!!!!!!xxx                          xxx     xxxx  ",
   "  xx                       xxx!!!!!xxx           xxx!!!!!xxxo      x       xxx  ",
   "  xx                         xx!!!xx          o    xx!!!xx                  xx  ",
   "  xx                          xx!xx          xxx    xxvxx                   xx  ",
   "  xxx                          xvx                                          xx  ",
   "  xxx            o                   xxx                                    xx  ",
   "  xx           xxxx                        o                                xx  ",
   "  xx          xxx                         xxx                               xx  ",
   "  xx        xxxxx                       xx!!!xx                          g  xx  ",
   "  xx   @   xxxxxxx         e          xxx!!!!!xxx          o         xxxxxxxxx  ",
   "  xxxxxxxxxxxxxxx!!!!!!xxxxxxx     xxxxx!!!!!!!xxxxx     xxxxx     xxx      xx  ",
   "  xxxxxxxxxxxxxxxvxxxvxxxxxxxx!!!!!xxx!!!!!xxx!!xxxx!!!!!!!!!!!!!!!xx     xxxx  ",
   "  xxx       xx          xxxxxxx!!!xxxxvxxvxxxxxvxxxxxx!!!!!!!!!!!!xxx       xx  ",
   "  xx                     xx   x!!!x     x  xxx     xxxxvxxx!xvxxxxxxxxx     xx  ",
   "  xx                           xxx          x             xxx               xx  ",
   "  xx                                                                        xx  "],
   ["                                                                                                             ",                                                                                                                                                                                
   "  xxxxxxxxxxxxxxxx                                                                                            ",
   "  xxx    xxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                                    ",
   "  xx          xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                                    ",
   "  xxx  @       xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                                    ",
   "  xxxxxxxx    xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                                    ",
   "  xx          xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx  ",
   "  xx          xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx  ",
   "  xx         xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx  ",
   "  xx   xxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxx  ",
   "  xx          xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx  ",
   "  xx              xxvxxxvxxxvxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx  ",
   "  x                 v     xxvxxxxxvxvxxxxvxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx  ",
   "  x                            xxxvxvxxxxvxxxv!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx  ",
   "  x                                         xvxvxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx  ",
   "  x                                           xvxxxxvxxxxv!!!!!!!xv!x!!!!!!!!!!!!!!!!!!xvxx!!!!!!!!xxxxxxxxx  ",
   "  x                                              xxx xxx  xxxvxxxx vx!xxxxv!!!!!!!!!!!xx  xvx!!v!!xxxx   xxx  ",
   "  x                                                       xxxvxxxx vxv   xvxxxx!xxxvxxx     xxv xxxx      xx  ",
   "  x                                                                 x          v                           x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                     g  x  ",
   "  x                                                                                                  xxxxxxx  ",
   "  x                                                                                               xxxxxxxxxx  ",
   "  x                                                 e                                    e        xxxxxxxxxx  ",
   "  x                                              xxxxxxx   xxxxxx                    xxxxxxxxxx   xxxxxxxxxx  ",
   "  x                                                                          e                   xxxxxxxxxxx  ",
   "  x                         e        x   xxx                            xxxxxxxxxx              xxxxx!!!!xxx  ",
   "  xx                  xxxxxxxxxxx!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxx!!!!!!!!!!!!!!xxx!!!!!!!!x  ",
   "  xxx              xxxxx!!!!!xxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!x  ",
   "  xxxx          xxxxxx!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
   ["                                  ",
	" x                              x ",
	" xo   o  oo  o  o  o   o o o   ox ",
	" x o o  o  o o  o  o o o o oo  ox ",
	" x  o   o  o o  o  o o o o o o ox ",
	" x  o   o  o o  o  o o o o o  oox ",
	" x  o    oo   oo    o o  o o   ox ",
	" x                              x ",
	" x                              x ",
	" x                    @         x ",
	" xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
	"                                    "],
  ];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
